name: Revert Commit

on:
  workflow_dispatch:

jobs:
  revert:
    runs-on: ubuntu-latest

    steps:
      - name: Чекaут репозитория
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          ref: test-new1
          submodules: recursive 
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Настройка Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Выполнение git revert
        run: |
          # Отменяем конкретный коммит без открытия редактора
          git revert --no-edit 0cb69b696c342df4768288b7b8e1949dc999a122

      - name: Пуш изменений в репозиторий
        run: |
          git push origin ${{ github.ref_name }}
