name: Cherry-pick Commit

on:
  workflow_dispatch:

jobs:
  cherry-pick:
    runs-on: ubuntu-latest

    steps:
      - name: Чекaут текущего репозитория
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          ref: test-new1
          submodules: false
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Настройка Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Подключение стороннего репозитория и cherry-pick коммита
        run: |
          # 1. Добавляем сторонний репозиторий как remote
          git remote add raikiri https://github.com/Sayemx18/kernel_xiaomi_sm8250.git

          # 2. Скачиваем его историю
          git fetch raikiri

          # 3. Выполняем cherry-pick конкретного коммита
          git cherry-pick e6321d5e359f7854e5344f837f63085aee2366f2

      - name: Пуш изменений в репозиторий
        run: |
          # 4. Отправляем примененный коммит в текущую ветку
          git push origin ${{ github.ref_name }}
